---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    ignore:
      - dependency-name: "com.stripe:stripe-java"
        # Stripe SDK 22.x needs refactoring on our end
        versions:
          - ">= 22"
      - dependency-name: "org.eclipse.persistence:org.eclipse.persistence.jpa"
        # org.eclipse.persistence.jpa 5 is incompatible with Guice 7, needs a lot of work on our end
        versions:
          - ">= 5"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - java
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    ignore:
      - dependency-name: "eclipse-temurin"
        versions:
          - "> 25"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - govuk-pay
      - docker
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - govuk-pay
      - github_actions
