package uk.gov.pay.connector.gateway.model.request;

import uk.gov.pay.connector.model.domain.GatewayAccountEntity;
import uk.gov.pay.connector.model.domain.RefundEntity;
import uk.gov.pay.connector.gateway.GatewayOperation;

public class RefundGatewayRequest implements GatewayRequest {

    private final GatewayAccountEntity gatewayAccountEntity;
    private final String amount;
    private final String transactionId;
    private final String reference;

    private RefundGatewayRequest(String transactionId, GatewayAccountEntity gatewayAccount, String amount, String reference) {
        this.transactionId = transactionId;
        this.gatewayAccountEntity = gatewayAccount;
        this.amount = amount;
        this.reference = reference;
    }

    public String getAmount() {
        return amount;
    }

    public String getTransactionId() {
        return transactionId;
    }

    @Override
    public GatewayAccountEntity getGatewayAccount() {
        return gatewayAccountEntity;
    }

    @Override
    public GatewayOperation getRequestType() {
        return GatewayOperation.REFUND;
    }

    /**
     * <p>
     * For Worldpay ->
     *          transactionId = The original charges.gateway_transaction_id generated by us <br>
     *          reference = our externalId for this refund, <b> this is our link to the worldpay refund transaction</b>
     * </p>
     *
     * <p>
     * For Smartpay ->
     *         transactionId = The original charges.gateway_transaction_id (a.k.a pspReference) given to us by smartpay at the payment AUTHORIZATION response. <br>
     *         reference = our externalId for this refund, <b> this is NOT our link to smartpay refund. its only a pass through value as far as smartpay is concerned </b> <br>
     *
     *        Smartpay does not respond with our reference when SUBMIT REFUND, however when they notify us REFUNDED they return
     *          -  Our `reference` we sent above will also be returned as `merchantReference`.
     *          - `transactionId` above will also be returned as `originalReference`.
     *          - Their reference to the Refund in smartpay will be returned as `pspReference`.
     * </p>
     */
    public static RefundGatewayRequest valueOf(RefundEntity refundEntity) {
        return new RefundGatewayRequest(
                refundEntity.getChargeEntity().getGatewayTransactionId(),
                refundEntity.getChargeEntity().getGatewayAccount(),
                String.valueOf(refundEntity.getAmount()),
                refundEntity.getExternalId());
    }

    public String getReference() {
        return reference;
    }
}
