package uk.gov.pay.connector.gateway.model;

public enum ErrorType {
    GENERIC_GATEWAY_ERROR,
    UNEXPECTED_HTTP_STATUS_CODE_FROM_GATEWAY,
    MALFORMED_RESPONSE_RECEIVED_FROM_GATEWAY,
    GATEWAY_URL_DNS_ERROR,
    GATEWAY_CONNECTION_TIMEOUT_ERROR,
    GATEWAY_CONNECTION_SOCKET_ERROR,
}
