package uk.gov.pay.connector.tasks.service;

public enum Connector3dsExemptionResultState {
    CONNECTOR_HAS_EXEMPTION_RESULT_NULL,
    CONNECTOR_HAS_EXEMPTION_RESULT_REQUESTED,
    CONNECTOR_HAS_EXEMPTION_RESULT_HONOURED,
    CONNECTOR_HAS_EXEMPTION_RESULT_REJECTED,
    CONNECTOR_HAS_EXEMPTION_RESULT_OUT_OF_SCOPE,
}
