package uk.gov.pay.connector.tasks.service;

public enum ConnectorExemption3dsRequestedState {
    CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_NULL,
    CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_OPTIMISED,
    CONNECTOR_HAS_EXEMPTION_3DS_REQUESTED_CORPORATE
}
