package uk.gov.pay.connector.tasks.service;

public enum LedgerExemptionState {
    LEDGER_EXEMPTION_NULL,
    LEDGER_HAS_EXEMPTION_WITH_REQUESTED_FALSE,
    LEDGER_EXEMPTION_REQUESTED_TRUE,
    LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_HONOURED,
    LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_REJECTED,
    LEDGER_EXEMPTION_REQUESTED_TRUE_AND_OUTCOME_OUT_OF_SCOPE,
    LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_HONOURED,
    LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_REJECTED,
    LEDGER_EXEMPTION_REQUESTED_TRUE_TYPE_CORPORATE_AND_OUTCOME_OUT_OF_SCOPE,
}
