package uk.gov.pay.connector.tasks.service;

public enum LedgerAuthorisationSummaryState {
    LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_TRUE,
    LEDGER_HAS_AUTHORISATION_SUMMARY_WITH_THREE_D_S_REQUIRED_FALSE,
    LEDGER_HAS_NO_AUTHORISATION_SUMMARY,
    LEDGER_HAS_SOMETHING_COMPLETELY_DIFFERENT
}
