name: Post Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: connector-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  publish-connector-consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-latest

    name: Publish and tag connector consumer pact
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Set up JDK 11
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag connector consumer pact
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pact-broker-test.cloudapps.digital \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} -DPACT_CONSUMER_TAG=master \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  ledger-provider-contract-tests:
    needs: publish-connector-consumer-contract-tests
    uses: alphagov/pay-ledger/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: connector
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  cardid-provider-contract-tests:
    needs: publish-connector-consumer-contract-tests
    uses: alphagov/pay-cardid/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: connector
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  provider-contract-tests:
    needs: tests
    uses: alphagov/pay-ci/.github/workflows/_run-provider-contract-tests.yml@master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - ledger-provider-contract-tests
      - cardid-provider-contract-tests
      - provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
